# Generated by Django 3.0.2 on 2020-01-27 01:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 1, 15, 35, 556568)),
        ),
    ]
