# Generated by Django 3.0.2 on 2020-01-27 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20200127_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='mydate',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 1, 20, 5, 37884)),
        ),
    ]
